<?php

declare(strict_types=1);

namespace Mafin\DTO\Casters;

use Spatie\DataTransferObject\FieldValidator;

class BoolValueCaster extends CustomizableValueCaster
{
    public function castValue($value, array $allowedTypes)
    {
        if (is_int($value) && in_array($value, [0, 1]) && in_array('boolean', $allowedTypes, true)) {
            return (bool) $value;
        }

        return parent::castValue($value, $allowedTypes); // TODO: Change the autogenerated stub
    }
}